# Generated by Django 4.2.5 on 2023-09-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_models_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='model',
            name='second_name',
        ),
        migrations.AddField(
            model_name='model',
            name='email',
            field=models.EmailField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='model',
            name='phone',
            field=models.IntegerField(default=True),
        ),
    ]
