# Generated by Django 4.2.5 on 2023-09-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_model_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='email',
        ),
        migrations.RemoveField(
            model_name='model',
            name='phone',
        ),
    ]
