# Generated by Django 4.2.5 on 2023-09-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_model_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='company',
            field=models.CharField(default='lc', max_length=100),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
