# Generated by Django 4.2.5 on 2023-09-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_model_company_alter_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
