# Generated by Django 4.2.5 on 2023-09-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_model_company_alter_model_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='company',
        ),
        migrations.RemoveField(
            model_name='model',
            name='quantity',
        ),
        migrations.AddField(
            model_name='model',
            name='Email',
            field=models.EmailField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='model',
            name='Phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
